server:
  port: 8080
spring:
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:testdb
    username: sa
  cache:
    type: redis
#    type: "none"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
### standalone
#    host: 172.19.170.67
#    port: 6379
### cluster
#    cluster:
#      nodes:
#        - xxx.xx.xxx.xxx:30001
#        - xxx.xx.xxx.xxx:30002
#        - xxx.xx.xxx.xxx:30001
#        - xxx.xx.xxx.xxx:30002
#        - xxx.xx.xxx.xxx:30001
#        - xxx.xx.xxx.xxx:30002
#      max-redirects: 3
    port: 6379
#    password: 123pwd
    sentinel:
      master: mymaster
      nodes:
        - 172.19.170.60:26379
        - 172.19.170.61:26379
        - 172.19.170.67:26379
    database: 1